// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PetClinicSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addNewOwner() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Kurtis");
    driver.FindElement(By.CssSelector(".form-horizontal")).Click();
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Connor");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("Big Street, 100");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Toronto");
    driver.FindElement(By.Id("telephone")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys("04467228");
    driver.FindElement(By.CssSelector(".addOwner")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".petOwner:nth-child(345) > .ownerFullName")).Text, Is.EqualTo("Kurtis Connor"));
    Assert.That(driver.FindElement(By.CssSelector(".petOwner:nth-child(345) > .ownerAddress")).Text, Is.EqualTo("Big Street, 100"));
    Assert.That(driver.FindElement(By.CssSelector(".petOwner:nth-child(345) > .ownerCity")).Text, Is.EqualTo("Toronto"));
    Assert.That(driver.FindElement(By.CssSelector(".petOwner:nth-child(345) > .ownerPhone")).Text, Is.EqualTo("04467228"));
    driver.Close();
  }
  [Test]
  public void addNewPet() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(345) a")).Click();
    driver.FindElement(By.CssSelector(".xd-container")).Click();
    driver.FindElement(By.CssSelector(".addNewPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("Asya");
    driver.FindElement(By.Name("birthDate")).Click();
    driver.FindElement(By.Name("birthDate")).SendKeys("2018/01/01");
    driver.FindElement(By.CssSelector(".form-horizontal")).Click();
    driver.FindElement(By.Id("type")).Click();
    {
      var dropdown = driver.FindElement(By.Id("type"));
      dropdown.FindElement(By.XPath("//option[. = 'cat']")).Click();
    }
    driver.FindElement(By.CssSelector(".savePet")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".petName")).Text, Is.EqualTo("Asya"));
    Assert.That(driver.FindElement(By.CssSelector(".petBirthDate")).Text, Is.EqualTo("2018/01/01"));
    Assert.That(driver.FindElement(By.CssSelector(".petType")).Text, Is.EqualTo("cat"));
    driver.Close();
  }
  [Test]
  public void editOwner() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(345) a")).Click();
    vars["ownerAddress"] = driver.FindElement(By.CssSelector(".ownerAddress")).Text;
    driver.FindElement(By.CssSelector(".editOwner")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(4)")).Click();
    driver.FindElement(By.Id("address")).SendKeys("Kyivska Street, 3");
    driver.FindElement(By.CssSelector(".updateOwner")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".ownerAddress")).Text, Is.Not.EqualTo("Big Street, 100"));
    driver.Close();
  }
  [Test]
  public void editPet() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(345) a")).Click();
    driver.FindElement(By.CssSelector(".editPet")).Click();
    driver.FindElement(By.Name("birthDate")).Click();
    driver.FindElement(By.Name("birthDate")).SendKeys("2018/03/02");
    driver.FindElement(By.CssSelector(".updatePet")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".petBirthDate")).Text, Is.Not.EqualTo("2018/01/01"));
    driver.Close();
  }
}
