// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VetTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addNewCorrectVet() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Peter");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Smith");
    driver.FindElement(By.Id("specialties")).Click();
    {
      var dropdown = driver.FindElement(By.Id("specialties"));
      dropdown.FindElement(By.XPath("//option[. = 'surgery']")).Click();
    }
    driver.FindElement(By.CssSelector(".saveVet")).Click();
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td)[166]")).Text, Is.EqualTo("Peter Smith"));
    Assert.That(driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td[2]/div)[54]")).Text, Is.EqualTo("surgery"));
    driver.Close();
  }
  [Test]
  public void editVet() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td[3]/button)[109]")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    vars["firstName"] = driver.FindElement(By.Id("firstName")).Text;
    driver.FindElement(By.Id("firstName")).SendKeys("Maria");
    driver.FindElement(By.Id("lastName")).Click();
    vars["lastName"] = driver.FindElement(By.Id("lastName")).Text;
    driver.FindElement(By.Id("lastName")).SendKeys("Smith");
    driver.FindElement(By.CssSelector(".mat-select-value")).Click();
    driver.FindElement(By.CssSelector("#mat-option-3 > .mat-option-pseudo-checkbox")).Click();
    driver.FindElement(By.CssSelector(".cdk-overlay-backdrop")).Click();
    driver.FindElement(By.CssSelector(".saveVet")).Click();
    Assert.That(driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td)[163]")).Text, Is.Not.EqualTo("firstName lastName"));
    driver.Close();
  }
  [Test]
  public void addNewIncorrectVet() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1320, 784);
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) > a")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("k");
    Assert.That(driver.FindElement(By.CssSelector(".help-block")).Text, Is.EqualTo("First name must be at least 2 characters long"));
    driver.FindElement(By.Id("firstName")).SendKeys("Daria");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Smith");
    driver.FindElement(By.Id("specialties")).Click();
    {
      var dropdown = driver.FindElement(By.Id("specialties"));
      dropdown.FindElement(By.XPath("//option[. = 'radiology']")).Click();
    }
    driver.FindElement(By.CssSelector(".saveVet")).Click();
    Assert.That(driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td)[163]")).Text, Is.EqualTo("Daria Smith"));
    Assert.That(driver.FindElement(By.XPath("(//tr[@id=\'vet\']/td[2])[55]")).Text, Is.EqualTo("radiology"));
    driver.Close();
  }
}
